---Defining the objects access and permission levels inside a kubernetes cluster for all namespaces---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mustafaclusterrole
rules:
  - apiGroups: [""]
    resources: ["pods", "deployments", "services"]
    verbs: ["create", "get", "watch", "delete", "list"]

  - apiGroups: ["apps"]
    resources: ["pods", "deployments", "services"]
    verbs: ["create", "get", "watch", "delete", "list"]
