---this manifest is about the giving the objects and their permission level that we can assign to a user---
---remember this applies only for one namespace---for multiple namespaces use clusterrole--
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mustafa-role
  namespace: dev
rules:
  - apiGroups: [""]
    resources: ["pods", "deployments", "services"]
    verbs: ["list", "get", "watch", "create", "delete"]
  - apiGroups: ["apps", ""]
    resources: ["pods", "deployments", "services"]
    verbs: ["list", "get", "watch", "create", "delete"]
